FROM cismet/cids-distribution-scaffold:latest

MAINTAINER Pascal Dihé <pascal.dihe@cismet.de>

LABEL de.cismet.cids.distribution.switchon.name="cids-distribution-switchon image" \
      de.cismet.cids.distribution.switchon.version="cids-distribution-switchon-1.0-0.1" \
      de.cismet.cids.distribution.switchon.descripton="cids SWITCH-ON Distribution Runtime Image"